### ISSUE TITLE
RAD implementation

### ISSUE THREAD

**Issue by KarlXing** [nicklashansen/dmcontrol-generalization-benchmark#11]
Hi, thank you for this work! I'm interested in the RAD implementation but found that the RAD agent just inherits the SAC. May I know how RAD in this implementation differs from SAC agent?

**Comment by nicklashansen** [comment]
Hi, great that you find it useful!
It is not so obvious but the random crop augmentation of RAD is applied in the replay buffer sampling [here](https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/ee658ceb449b884812149b922035197be8e28c87/src/utils.py#L91), and image size before and after crop is specified [here](https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/ee658ceb449b884812149b922035197be8e28c87/src/arguments.py#L91) for RAD. There is no difference between SAC and RAD aside from random crop augmentation.

**Comment by KarlXing** [comment]
I see. Thank you for your quick response!
