### ISSUE TITLE
Unable to find the robotic manipulation environment.

### ISSUE THREAD

**Issue by darshitajain** [nicklashansen/dmcontrol-generalization-benchmark#12]
Thank you for your contribution. I would like to use the robotic manipulation environment (pushing the cube to the location of the red disc) used in the paper- Generalization in Reinforcement Learning by Soft Data Augmentation. Is this environment publicly available for everyone to use?

@nicklashansen Request your help.

**Comment by nicklashansen** [comment]
Hi, glad to hear that you're interested in our work. The robot environments used for the paper are not made public, but we have open-sourced a similar environment with 4 tasks (including push) here: https://github.com/jangirrishabh/look-closer
It differs in subtle ways (visuals, robot, reward etc.) but is qualitatively similar.
