### ISSUE TITLE
Reproductibility SODA and SVEA conv

### ISSUE THREAD

**Issue by AdilZouitine** [nicklashansen/dmcontrol-generalization-benchmark#13]
Hi Nicklas, 
Thank you for your high-quality repo. 
We have trouble reproducing your results on `finger spin` with `SODA` and `SVEA` (we have between 500 and 600).
Even in training, we don't achieve the performance shown.
Are there any special settings or configurations for this environment?

Best regards

**Comment by nicklashansen** [comment]
Hi Adil, did you figure out the problem? We use an action repeat of 2 for this task. Depending on the number of seeds that you have run, I also wouldn't rule out that there's just a bad seed, it's RL after all.

**Comment by AdilZouitine** [comment]
Hi, I figured out the problem! 
Thanks!

**Comment by tungts1101** [comment]
@AdilZouitine May I know what is the problem? We are trying to reproduce the result but the loss does not update after 290K steps.
