### ISSUE TITLE
TypeError: make() got an unexpected keyword argument 'is_distracting_cs'

### ISSUE THREAD

**Issue by Guozheng-Ma** [nicklashansen/dmcontrol-generalization-benchmark#15]
Hello,

When I ran the command `python3 src/train.py --algorithm sac --seed 0`, I got this error :

```
Traceback (most recent call last):
  File "../src/train.py", line 150, in <module>
    main(args)
  File "../src/train.py", line 50, in main
    mode='train'
  File "/home/mgz_21/0_Project/DMConrol-GB/src/env/wrappers.py", line 48, in make_env
    background_dataset_paths=paths
TypeError: make() got an unexpected keyword argument 'is_distracting_cs'

```

My main packages version as:
```
cudatoolkit               11.0.221             
dm-control                0.0.318066097
numpy                      1.19.5
python                    3.7.6
torch                     1.7.1
```

Thanks!

**Comment by nicklashansen** [comment]
Hi! Did you follow our setup instructions and installed our custom packages? We use custom versions for DMControl and dmc2gym: https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/main/setup/install_envs.sh
Note that this version of DMControl is slightly outdated and requires a MuJoCo license. You can obtain a free license at MuJoCo's website. Let me know if that doesn't solve the issue!

**Comment by Guozheng-Ma** [comment]
Thank you so much for the quick reply. I tried to reinstall your custom packages as the setup instructions, but I still face the issue as:

```
Traceback (most recent call last):
  File "src/train.py", line 150, in <module>
    main(args)
  File "src/train.py", line 50, in main
    mode='train'
  File "/home/mgz_21/0_Project/DMControl-GB/src/env/wrappers.py", line 48, in make_env
    background_dataset_paths=paths
  File "/home/mgz_21/0_Project/DMControl-GB/src/env/dmc2gym/dmc2gym/__init__.py", line 36, in make
    if not env_id in gym.envs.registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'
```

**Comment by MyIDis12138** [comment]
> Thank you so much for the quick reply. I tried to reinstall your custom packages as the setup instructions, but I still face the issue as:
> 
> ```
> Traceback (most recent call last):
>   File "src/train.py", line 150, in <module>
>     main(args)
>   File "src/train.py", line 50, in main
>     mode='train'
>   File "/home/mgz_21/0_Project/DMControl-GB/src/env/wrappers.py", line 48, in make_env
>     background_dataset_paths=paths
>   File "/home/mgz_21/0_Project/DMControl-GB/src/env/dmc2gym/dmc2gym/__init__.py", line 36, in make
>     if not env_id in gym.envs.registry.env_specs:
> AttributeError: 'dict' object has no attribute 'env_specs'
> ```

I have met the same issue like this, it seems the dmc2gym didn't work

**Comment by siaoliu** [comment]
use gym==0.24 to solve this problem
