### ISSUE TITLE
Question about robot-push

### ISSUE THREAD

**Issue by siaoliu** [nicklashansen/dmcontrol-generalization-benchmark#18]
Could you give me some help about the implements about Robotic manipulation. Looking forward your help. I'm not find such task.

**Comment by nicklashansen** [comment]
Hi, glad to hear that you're interested in our work. The robot environments used for the paper are not made public, but we have open-sourced a similar environment with 4 tasks (including push) here: https://github.com/jangirrishabh/look-closer
It differs in subtle ways (visuals, robot, reward etc.) but is qualitatively similar.
