### ISSUE TITLE
`view_as_windows` not defiled

### ISSUE THREAD

**Issue by geyang** [nicklashansen/dmcontrol-generalization-benchmark#2]
here: https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/main/src/augmentations.py#L156

Maybe this function is not currently used, which is why.

**Comment by nicklashansen** [comment]
Thank you! This has been fixed now in commit https://github.com/nicklashansen/dmcontrol-generalization-benchmark/commit/00c6a5d2a3a14e735068ea07775f42bd1150440d
