### ISSUE TITLE
Question about data augmentation on target network

### ISSUE THREAD

**Issue by lee15253** [nicklashansen/dmcontrol-generalization-benchmark#21]
Thank you for your great work.

Could you please clarify whether the target network undergoes any data augmentation, including random shift (i.e., weak augmentation), in the SVEA? I am unsure if the random shifts are applied or not, in the target network.

Thank you.

**Comment by nicklashansen** [comment]
Yes! You are correct that random shift should be applied to both `obs` and `next_obs` in SVEA. This was accidentally changed in PR https://github.com/nicklashansen/dmcontrol-generalization-benchmark/commit/35a1eed87f72d3c9881c425fd83604c756849e56 but I have reverted it now in commit https://github.com/nicklashansen/dmcontrol-generalization-benchmark/commit/ff9c0aa8d47685ed972414c67f1b7225e37ff85e.
