### ISSUE TITLE
Confusion about Capacity of ReplayBuffer

### ISSUE THREAD

**Issue by RayYoh** [nicklashansen/dmcontrol-generalization-benchmark#25]
Hello authors, thx for your great work.
I have one question about the capacity of the replaybuffer [code](https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/a81df68838757ca55c19ac5f9fd8cd04bf8a942c/src/train.py#L75C27-L75C27). But acording to the original [DrQ](https://github.com/denisyarats/drq/blob/dd040f144ed8f696c7db35087cd80c87372edb64/train.py#L82) code, I find that they use a hyperparameter to set the cabicity and their default parameter is 100000. Is there any reasons to set the capacity by train_steps.

**Comment by nicklashansen** [comment]
Hi, thanks for your question and apologies that it took a while to get back to you. Setting the capacity to # steps ensures that all samples are kept during training. If you have the memory for it, that should yield you the best results. If you are constrained on memory you can reduce the capacity at the cost of performance. I hope this clears things up!

**Comment by RayYoh** [comment]
> Hi, thanks for your question and apologies that it took a while to get back to you. Setting the capacity to # steps ensures that all samples are kept during training. If you have the memory for it, that should yield you the best results. If you are constrained on memory you can reduce the capacity at the cost of performance. I hope this clears things up!

Got that, Thank you very much.
