### ISSUE TITLE
How to calculate the std mentioned in the article?

### ISSUE THREAD

**Issue by gemcollector** [nicklashansen/dmcontrol-generalization-benchmark#4]
Hello～ How to calculate the std.deviation in the paper? Should I record all the episode rewards in every episode from different seeds and calculate their std. deviation？Or just record the mean of 100 episodes in different seeds，and calculate the std. deviation among these mean values?

**Comment by nicklashansen** [comment]
Hi, we compute the standard deviation over the mean episode returns of each seed. For figures this is done continuously over the course of training, for tables we compute it for the final policy.
