### ISSUE TITLE
cnn-encoder part of Actor in sac.py would never be updated?

### ISSUE THREAD

**Issue by emigmo** [nicklashansen/dmcontrol-generalization-benchmark#5]
Hi, here
https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/ee658ceb449b884812149b922035197be8e28c87/src/algorithms/sac.py#L104

As the detach=True, all the cnn-encoder parts of the actor would not be updated? is it right? or you do not want to update the cnn encoder of the actor?

or am I missing something?

**Comment by nicklashansen** [comment]
Hi, the cnn layers of the encoder (shared_cnn in the code) are shared between actor and critic, and only the critic updates those layers. We largely follow the implementation of [pytorch_sac](https://github.com/denisyarats/pytorch_sac).
