### ISSUE TITLE
Results on other domains

### ISSUE THREAD

**Issue by shreyask3107** [nicklashansen/dmcontrol-generalization-benchmark#7]
Hi, do we need to tune parameters for domains like humanoid?
I tried to run the code and the training is as close to the results claimed for the walker domain, however, when I use the same parameters for humanoid, the reward doesn't even go to double digits. Is this expected or am I expected to consider some more factors?

**Comment by nicklashansen** [comment]
I have not benchmarked the algorithms in this repo on other domains, but they all use SAC as backbone and to my knowledge there exists no SAC implementation that solves the humanoid tasks from pixels.

**Comment by shreyask3107** [comment]
Thanks!
