### ISSUE TITLE
Issues with agents trained with Humanoid domain

### ISSUE THREAD

**Issue by shreyask3107** [nicklashansen/dmcontrol-generalization-benchmark#9]
Hi, when I train any model with any task of humanoid domain, I observe that the agent does not move at all. Could you point out to any possible error which I will be able to tackle?

**Comment by nicklashansen** [comment]
Hi, to my knowledge there exists no open source implementation of SAC that is able to solve humanoid from pixels, and all methods in this repo use SAC as backbone learning algo. Perhaps https://github.com/facebookresearch/drqv2 may be of interest to you, they recently solved the humanoid tasks using DDPG.

**Comment by tejassp2002** [comment]
@nicklashansen, are you thinking of adding DrQ-v2 in this benchmark, to me it seems like a simple extension of DrQ?

Thanks!

**Comment by nicklashansen** [comment]
Hi, no plans at this time. DrQ-v2 is based on DDPG and there are quite a few changes to hyperparameters, replay buffer, code-level optimization etc. compared to this repo / the DrQ codebase so it is not a trivial port and would likely hurt clarity. If you're interested in benchmarking DrQ-v2 on DMC-GB, it is probably easier to port the benchmark envs to their codebase for evaluation.

**Comment by tejassp2002** [comment]
That's a great idea. Thanks for the clarification @nicklashansen!
